# Kill idle connections older than 10 minutes
name: Kill idle connections

on:
#  schedule:
#    - cron: '0 */3 * * * '  # every 3 hours
#    - cron: '0 5 * * *'  # every day 5am GMT (12/1am EST/EDT)
  workflow_dispatch:
jobs:
  kill-idle-cons:
    runs-on: ubuntu-latest
    steps:
      # Set up
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: 'Create env file'
        run: |
          mkdir env
          echo "${{ secrets.ENV_FILE }}" > env/.env

      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          # Reactivate install upgrades of pip, wheel, &/or setuptools if needed
          # python -m pip install --upgrade pip
          # pip install --upgrade wheel
          # pip install --upgrade setuptools
          # VS Hub SDK w/ OAuth disabled: https://github.com/jhu-bids/TermHub/issues/863
          # TOKEN=$(grep '^PALANTIR_ENCLAVE_AUTHENTICATION_BEARER_TOKEN=' env/.env | cut -d'=' -f2)
          # python3 -m pip install vshub_sdk --upgrade --extra-index-url "https://:${TOKEN}@unite.nih.gov/artifacts/api/repositories/ri.artifacts.main.repository.9bc9cc56-4b8c-4560-9bfb-fba8ade55246/contents/release/pypi/simple" --extra-index-url "https://:${TOKEN}@unite.nih.gov/artifacts/api/repositories/ri.foundry-sdk-asset-bundle.main.artifacts.repository/contents/release/pypi/simple"
          pip install -r requirements.txt

      # Run the action
      - name: Kill idle connections
        run: make kill-idle-cons
